server:
  port: ":8087"
  ip: "47.93.22.146"

database:
  port: "3306"
  user: "dms"
  pass: "lcx-machine0918LMY"
  name: "manidb"

router:
  default_all_action_file: "1"
  open_all_action_file: "1"
  default_image_action_file: "1"
